### ISSUE TITLE
Flatten prefix structure in transfer script

### ISSUE THREAD

**Issue by jtherrmann** [ASFHyP3/hyp3-flood-monitoring#42]
[Here](https://github.com/ASFHyP3/hyp3-flood-monitoring/blob/develop/transfer-products/src/transfer_products.py#L55) it looks like we're transferring products into a nested prefix structure (`<job-name>/<job-id>/`), but after discussing with @hjkristenson it sounds like we want all the files under a common prefix. I think this will just require changing that line to:

```python3
target_key = f'{target_prefix}/{filename}'
```

**Comment by asjohnston-asf** [comment]
addressed by https://github.com/ASFHyP3/hyp3-flood-monitoring/pull/44
